module.exports = [
  {
    id: 0,
    question: "Who is the father of C language?",
    options: [
      "Steve Jobs",
      "James Gosling",
      "Dennis Ritchie",
      "Rasmus Lerdorf",
    ],
    correct: "Dennis Ritchie",
    hint: "",
    fact: "Dennis Ritchie is the father of C Programming Language. C programming language was developed in 1972 at American Telephone & Telegraph Bell Laboratories of USA.",
  },
  {
    id: 1,
    question:
      "Which of the following declaration is not supported by C language?",
    options: [
      "String str;",
      "char *str;",
      "float str = 3e2;",
      "All of the above",
    ],
    correct: "String str;",
    hint: "",
    fact: " It is legal in Java, but not in C language.",
  },
  {
    id: 2,
    question: " In C language, FILE is of which data type?",
    options: ["int", "char*", "struct", "None of the above"],
    correct: "struct",
    hint: "",
    fact: "",
  },
  {
    id: 3,
    question: "Who invented Java Programming?",
    options: [
      "Steve Jobs",
      "James Gosling",
      "Dennis Ritchie",
      "Rasmus Lerdorf",
    ],
    correct: "James Gosling",
    hint: "",
    fact: " Java programming was developed by James Gosling at Sun Microsystems in 1995. James Gosling is well known as the father of Java.",
  },
  {
    id: 4,
    question: " Which one of the following is not a Java feature?",
    options: [
      "Object-oriented",
      " Use of pointers",
      "Portable",
      "Dynamic and Extensible",
    ],
    correct: " Use of pointers",
    hint: "",
    fact: "Pointers is not a Java feature. Java provides an efficient abstraction layer for developing without using a pointer in Java. Features of Java Programming are Portable, Architectural Neutral, Object-Oriented, Robust, Secure, Dynamic and Extensible, etc.",
  },
  {
    id: 5,
    question: "Which environment variable is used to set the java path?",
    options: ["MAVEN_Path", "JavaPATH", "JAVA", "JAVA_HOME"],
    correct: "JAVA_HOME",
    hint: "",
    fact: "JAVA_HOME is used to store a path to the java installation",
  },
  {
    id: 6,
    question: "Which of the following is not javascript data types?",
    options: [
      "Null type",
      "Undefined type",
      "Number type",
      " All of the mentioned",
    ],
    correct: " All of the mentioned",
    hint: "",
    fact: " JavaScript is a dynamic, loosely typed language. Variables in JavaScript aren't tied to any specific value type, and each variable can be assigned and reassigned to values of all the types",
  },
  {
    id: 7,
    question:
      "Which is the main entry point to all client-side JavaScript features and APIs?",
    options: ["Position", "Window", "Standard", "Location"],
    correct: "Window",
    hint: "",
    fact: "All client-side JavaScript features and APIs are accessed through the Window object. It represents a web browser window or frame, and the identifier window can be used to refer to it.",
  },
  {
    id: 8,
    question:
      "Which of the following can be used to call a JavaScript Code Snippet?",
    options: ["Function/Method", "Preprocessor", "Triggering Event", "RMI"],
    correct: "Function/Method",
    hint: "",
    fact: "A function call to the element on which JavaScript is to be run can be used to invoke JavaScript code. Other techniques include onclick, onload, and onsubmit, among others.",
  },
  {
    id: 9,
    question: "Who developed Python Programming Language?",
    options: [
      "Wick van Rossum",
      "Rasmus Lerdorf",
      "Guido van Rossum",
      "Niene Stom",
    ],
    correct: "Guido van Rossum",
    hint: "",
    fact: "Python language is designed by a Dutch programmer Guido van Rossum in the Netherlands.",
  },
  {
    id: 10,
    question: "All keywords in Python are in _________",
    options: [
      "Capitalized",
      "lower case",
      "UPPER CASE",
      "None of the mentioned",
    ],
    correct: "None of the mentioned",
    hint: "",
    fact: "True, False and None are capitalized while the others are in lower case.",
  },
  {
    id: 11,
    question:
      "Python supports the creation of anonymous functions at runtime, using a construct called-?",
    options: ["pi", "anonymous", "lambda", "none of the mentioned"],
    correct: "lambda",
    hint: "",
    fact: "Python supports the creation of anonymous functions (i.e. functions that are not bound to a name) at runtime, using a construct called lambda. Lambda functions are restricted to a single expression. They can be used wherever normal functions can be used.",
  },
  {
    id: 12,
    question: "Which of the following is basis for SQL?",
    options: ["SQL Server", "DBMS", "RDBMS", "Oracle"],
    correct: "RDBMS",
    hint: "",
    fact: "RDBMS is the basis for SQL, and for all modern database systems such as MS SQL Server, IBM DB2, Oracle, MySQL and Microsoft Access.",
  },
  {
    id: 13,
    question: " What is the full form of PL in PL/SQL?",
    options: [
      "Programming Language",
      "Programming Logic",
      "Procedural Language",
      "Procedural Logic",
    ],
    correct: "Procedural Language",
    hint: "",
    fact: "PL in PL/SQL stands for Procedural Language. It is a block structured language that enables developers to combine the power of SQL with procedural language.",
  },
  {
    id: 14,
    question: "The SQL LIKE operator is used in which of the following clause?",
    options: ["Having", "Select", "Where", "Group by"],
    correct: "Where",
    hint: "",
    fact: "The SQL LIKE operator is used in a WHERE clause to search for a specified pattern in a column.",
  },
];
