module.exports = [
  {
    id: 0,
    question: " In C language, FILE is of which data type?",
    options: ["int", "char*", "struct", "None of the above"],
    correct: "struct",
    hint: "",
    fact: "",
  },
  {
    id: 1,
    question: "Who invented Java Programming?",
    options: [
      "Steve Jobs",
      "James Gosling",
      "Dennis Ritchie",
      "Rasmus Lerdorf",
    ],
    correct: "James Gosling",
    hint: "",
    fact: " Java programming was developed by James Gosling at Sun Microsystems in 1995. James Gosling is well known as the father of Java.",
  },
  {
    id: 2,
    question:
      "Which type of dragon does Viktor Krum face in the first task of the Triwizard Tournament?",
    options: [
      "Hungarian Horntail",
      " Chinese Fireball",
      "Swedish Short-Snout",
      "Common Welsh Green",
    ],
    correct: "Chinese Fireball",
    hint: "",
    fact: "The Hungarian Horntail is the most dangerous of the four dragons.",
  },
  {
    id: 3,
    question: "Where Did It Originate:Nasi Goreng",
    options: ["Indonesia", "Bahrain", "Mexico", "Vietnam"],
    correct: "Indonesia",
    hint: "South-East Asian Country",
    fact: "Fried rice dish, usually cooked with pieces of meat and vegetables",
  },
  {
    id: 4,
    question:
      "Which film series from the 2000s stars Tom Cruise as Ethan Hunt?",
    options: [
      "James Bond: Casino Royale",
      "Mission: Impossible",
      "The Bourne Identity",
      "Die Hard: Mission Impossible",
    ],
    correct: "Mission: Impossible",
    hint: "This film series features high-stakes espionage missions led by a skilled agent named Ethan Hunt.",
    fact: "",
  },
  {
    id: 5,
    question: "Who played Sharkboy in Sharkboy and Lavagirl?",
    options: ["Taylor Lautner", "Zac Efron", "Jake Gyllenhaal", "Shia LaBeouf"],
    correct: "Taylor Lautner",
    hint: "He's known for his role as a werewolf in another popular film series",
    fact: "",
  },
  {
    id: 6,
    question: "Can you Guess The Food Anagram:AMOK AS US (8)",
    options: ["Soak Maus", "Souma Kas", "Moussaka", "Amass You"],
    correct: "Moussaka",
    hint: "A dish made with layers of eggplant, minced meat, and tomato sauce, topped with a creamy béchamel sauce",
    fact: "",
  },
  {
    id: 7,
    question: "What is the most stolen food in the world?",
    options: ["Cheese", "Bread", "Milk", "Chocolate"],
    correct: "Cheese",
    hint: "Made by using milk.",
    fact: "",
  },
  {
    id: 8,
    question: "True or False: Apples belong to the rose family.",
    options: ["Partially True", "False", "True", "Partially False"],
    correct: "True",
    hint: "",
    fact: "",
  },
  {
    id: 9,
    question:
      "True or False: Oysters and Lobsters used to be the food of the working class.",
    options: ["Partially True", "False", "True", "Partially False"],
    correct: "True",
    hint: "",
    fact: "",
  },
  {
    id: 10,
    question:
      "Can you name the actor who plays Darth Vader in the Star Wars movies?",
    options: ["David Prowse", "Harrison Ford", "Oscar Isaac", "John Boyega"],
    correct: "David Prowse",
    hint: "",
    fact: "",
  },
  {
    id: 11,
    question: "Name the teen heartthrob who played the role of Cedric Diggory.",
    options: [
      "Robert Pattinson",
      "Rupert Grint",
      "Daniel RadCliffe",
      "Tom Felton",
    ],
    correct: "Robert Pattinson",
    hint: "",
    fact: "",
  },
  {
    id: 12,
    question:
      "Which of the following dismissals is NOT a valid way to get out?",
    options: ["Bailed", "Caught", "Run Out", "Bowled"],
    correct: "Bailed",
    hint: "",
    fact: "",
  },
  {
    id: 13,
    question: "What is a cricket ball made of?",
    options: [
      "Rubber",
      "Leather",
      " Leather Outer/Cork Inner",
      "Leather Outer/Rubber Inner",
    ],
    correct: " Leather Outer/Cork Inner",
    hint: "",
    fact: "",
  },
  {
    id: 14,
    question: "What is the largest dog breed in the world?",
    options: [
      "Scottish Deerhound",
      "Great Pyrenees",
      " Greyhound",
      "English Mastiff",
    ],
    correct: "English Mastiff",
    hint: "",
    fact: "",
  },
  {
    id: 15,
    question: "How many teeth do normal adult dogs have?",
    options: ["42", "36", "44", "69"],
    correct: "42",
    hint: "",
    fact: "",
  },
  {
    id: 16,
    question: "Where was England legend David Beckham born?",
    options: ["Manchester", "Norwich", "London", "Carlisle"],
    correct: "London",
    hint: "",
    fact: "",
  },
  {
    id: 17,
    question: "The SQL LIKE operator is used in which of the following clause?",
    options: ["Having", "Select", "Where", "Group by"],
    correct: "Where",
    hint: "",
    fact: "The SQL LIKE operator is used in a WHERE clause to search for a specified pattern in a column.",
  },
  {
    id: 18,
    question: "Guess The Anagrams:ENTIRE REGION",
    options: ["Erogentirn", "Tonerigern", "Girenteron", "Orienteering"],
    correct: "Orienteering",
    hint: "",
    fact: "",
  },
  {
    id: 19,
    question: "Guess The Anagrams:SNOUT BAIL",
    options: [" Usain Bolt", "Justin Gatlin", "Allyson Felix", "Mo Farah"],
    correct: " Usain Bolt",
    hint: "Atheletics",
    fact: "",
  },
  {
    id: 20,
    question: "True or False: You can hypnotise a chicken?",
    options: ["Partially True", "False", "True", "Partially False"],
    correct: "True",
    hint: "",
    fact: "",
  },
  {
    id: 21,
    question:
      "True or False: Coral (in coral reefs) are plants and not animals?",
    options: ["Partially True", "False", "True", "Partially False"],
    correct: "Flse",
    hint: "",
    fact: "",
  },
  {
    id: 22,
    question: "Guess The Anagram: RAPTOR",
    options: ["Parrot", "Raptor", "Trapor", "Raprot"],
    correct: "Parrot",
    hint: "",
    fact: "",
  },
  {
    id: 23,
    question: "Guess The Anagrams: SOCCER IDOLS",
    options: ["Crocodiles", "Crockodiles", "Socerlodes", "Idolcress"],
    correct: "Crocodiles",
    hint: "",
    fact: "",
  },
  {
    id: 24,
    question: "What is the name of the horse of Alexander the Great?",
    options: ["Copenhagen", "Comanche", "Bucephalus", "Chaitak"],
    correct: "Bucephalus",
    hint: "",
    fact: "",
  },
  {
    id: 25,
    question: "Which of the following is not javascript data types?",
    options: [
      "Null type",
      "Undefined type",
      "Number type",
      " All of the mentioned",
    ],
    correct: " All of the mentioned",
    hint: "",
    fact: " JavaScript is a dynamic, loosely typed language. Variables in JavaScript aren't tied to any specific value type, and each variable can be assigned and reassigned to values of all the types",
  },
  {
    id: 26,
    question: "All keywords in Python are in _________",
    options: [
      "Capitalized",
      "lower case",
      "UPPER CASE",
      "None of the mentioned",
    ],
    correct: "None of the mentioned",
    hint: "",
    fact: "True, False and None are capitalized while the others are in lower case.",
  },
  {
    id: 27,
    question:
      "Python supports the creation of anonymous functions at runtime, using a construct called __________",
    options: ["pi", "anonymous", "lambda", "none of the mentioned"],
    correct: "lambda",
    hint: "",
    fact: "Python supports the creation of anonymous functions (i.e. functions that are not bound to a name) at runtime, using a construct called lambda. Lambda functions are restricted to a single expression. They can be used wherever normal functions can be used.",
  },
];
